#!/bin/bash

echo "🎬 Setting up IPTV for your streaming app..."
echo ""
echo "Step 1: Open xTeve web interface"
open http://localhost:34400/web/
echo "✅ Opening xTeve in browser..."
echo ""
echo "Step 2: Add M3U Playlist"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "In xTeve web interface:"
echo "  1. Click 'Playlist' in left menu"
echo "  2. Click 'New' or '+' button"
echo "  3. Enter these details:"
echo ""
echo "     Name: Free IPTV"
echo "     Type: M3U"
echo "     URL:  https://iptv-org.github.io/iptv/index.m3u"
echo ""
echo "  4. Click 'Save'"
echo "  5. Click 'Update' to fetch channels"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Step 3: Map Channels"
echo "  1. Go to 'Mapping' tab"
echo "  2. Select channels you want"
echo "  3. Assign channel numbers"
echo "  4. Click 'Save'"
echo ""
echo "Step 4: Test"
echo "  Check: http://localhost:34400/lineup.json"
echo ""
read -p "Press Enter when done to check channels..."

echo ""
echo "Checking for channels..."
CHANNELS=$(curl -s http://localhost:34400/lineup.json | grep -o "GuideName" | wc -l)
echo "Found $CHANNELS channels!"
echo ""
echo "✅ Setup complete! Reload your React Native app to see channels."
